# Importing Numpy

In [2]:
import numpy as np

# Creating a Numpy Array

In [10]:
#One dimension
np.array([4,3,2])

array([4, 3, 2])

In [12]:
np.array([[4,3,2],[2,1,0]])

array([[4, 3, 2],
       [2, 1, 0]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.full((2,3,4),[1,2,3,4])


array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [21]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Selecting Values

In [23]:
#One Dimension
var = np.array([4,3,2])
var[0]

4

In [7]:
#Two Dimension
var = np.array([[4,3,2],[2,1,0]])
var[0,:]
var[0][:]
var

array([[4, 3, 2],
       [2, 1, 0]])

# Functions
.mean()
.min()
.sqrt()

In [29]:
var = np.array([4,3,2])
var.mean()
np.mean(var)

3.0

In [32]:
np.sqrt(var)


array([[2.        , 1.73205081, 1.41421356],
       [1.41421356, 1.        , 0.        ]])

In [34]:
np.min(var)
var.min()

0

# Difference between a List and Numpy array

In [39]:
A_list = ['a',1,True]
np_array = np.array(['a',1,True])
print('Regular list: ', A_list, type(A_list))
print('Numpy array: ', np_array, type(np_array))

Regular list: ['a', 1, True] <class 'list'>
Numpy array:  ['a' '1' 'True'] <class 'numpy.ndarray'>


## Brodcasting

In [40]:
A_list = [2,4,6] *2
np_array = np.array([2,4,6]) *2

print('Regular list: ', A_list)
print('Numpy array: ', np_array)


Regular list: [2, 4, 6, 2, 4, 6]
Numpy array:  [ 4  8 12]


In [54]:
A_list = [2,4,6]
A_list_2 = [2,4,6]
np_array = np.array([2,4,6])
np_array_2 = np.array([2,4,6])

print('Regular list: ', A_list + A_list_2)
print('Numpy array: ', np_array + np_array_2)

Regular list:  [2, 4, 6, 2, 4, 6]
Numpy array:  [ 4  8 12]


# Subsetting and Indexing

In [50]:
A_list = [2,4,6,8,10,12] 
np_array = np.array([2,4,6,8,10,12]) 
print('Regular list: ', A_list[0:5:2])
print('Numpy array: ', np_array[0:5:2])



Regular list:  [2, 6, 10]
Numpy array:  [ 2  6 10]


TypeError: '>' not supported between instances of 'list' and 'int'

In [51]:
#print('Regular list: ', A_list[A_list > 4])
print('Numpy array: ', np_array[np_array > 4])

Numpy array:  [ 6  8 10 12]
